import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

type Props = {
  getServerSidePropsLocale: string | undefined;
  middlewareLocale: string | undefined;
  middlewareDefaultLocale: string | undefined;
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const getServerSideProps = async ({ req, locale }: any) => {
  const headers = new Headers(req.headers);
  return {
    props: {
      getServerSidePropsLocale: locale,
      middlewareLocale: headers.get("middlewarelocale") ?? null,
      middlewareDefaultLocale: headers.get("middlewareDefaultLocale") ?? null,
    },
  };
};

export default function Home(props: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div>
            {Object.entries(props).map(([key, value]) => (
              <div key={key}>
                <pre>{key}</pre>: {value}
              </div>
            ))}
          </div>
        </main>
      </div>
    </>
  );
}
