import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Geist, Geist_Mono } from "next/font/google";

type Props = {
  query: unknown;
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const getServerSideProps = async ({ req, query }: any) => {
  console.log(query);

  return {
    props: {
      query: req.query ?? "",
    },
  };
};

export default function Home(props: Props) {
  console.log(props);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div>Hello</div>
        </main>
      </div>
    </>
  );
}
